### ISSUE TITLE
Router breaks with x-oada-ensure-link header on GET

### ISSUE THREAD

**Issue by sanoel** [OADA/server#114]
Run any normal GET and leave the `x-oada-ensure-link` header and it results in `{
  "message": "Route GET:/bookmarks/services/fl-sync/ not found",
  "error": "Not Found",
  "statusCode": 404
}`

Can we ignore the header if it isn't a POST?

**Comment by awlayton** [comment]
The header is for PUT and POST. I don't know that we should ignore it for
other methods. It should probably give a better error though.

**Comment by awlayton** [comment]
@N-give could you fix it so that this returns a 400 with a message like `X-OADA-Ensure-Link not allowed for this method` or something? I would like to have a better error code but I can't think of one.

400 should be less confusing than 404 at least.

**Comment by awlayton** [comment]
Addressed in #142
